section: screens
	DESKTOP-BJNR3KH:
	mac:
end

section: links
	DESKTOP-BJNR3KH:
		right = mac
	mac:
		left = DESKTOP-BJNR3KH
end

section: aliases
	mac:
		ESKui-MacBookPro.local
		MacBook-Pro
		MacBook-Pro.local
		Johneybi-MacBook-Pro
		Johneybi-MacBook-Pro.local
end

section: remaps
	mac:
		right_alt.alone = f18
		right_alt.hold = right_alt

		shift+space = control+space
		control+c = command+c
		control+v = command+v
		control+x = command+x
		control+z = command+z
		control+y = command+shift+z
		control+a = command+a
		control+s = command+s
		control+n = command+n
		control+f = command+f
		control+w = command+w
		control+t = command+t
		control+b = command+b
		control+i = command+i
		control+g = command+g
		control+l = command+l
		control+r = command+r

		alt+f4 = command+q

		shift+home = command+shift+left
		shift+end = command+shift+right
		control+left = option+left
		control+right = option+right
end

section: options
end
